package com.example.financial_info.entity;

import java.io.Serializable;
import java.util.Date;

public class Quotation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private String sCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.datetime
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Date datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.time_interval
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Byte timeInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.now_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float nowPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.open_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float openPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.close_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float closePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.highest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float highest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.lowest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float lowest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.volume
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.turnover
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Long turnover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.turnover_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float turnoverRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.amplitude
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float amplitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.change_amount
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Long changeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotation.change_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Float changeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Quotation(String sCode, Date datetime, Byte timeInterval, Float nowPrice, Float openPrice, Float closePrice, Float highest, Float lowest, Long volume, Long turnover, Float turnoverRate, Float amplitude, Long changeAmount, Float changeRate) {
        this.sCode = sCode;
        this.datetime = datetime;
        this.timeInterval = timeInterval;
        this.nowPrice = nowPrice;
        this.openPrice = openPrice;
        this.closePrice = closePrice;
        this.highest = highest;
        this.lowest = lowest;
        this.volume = volume;
        this.turnover = turnover;
        this.turnoverRate = turnoverRate;
        this.amplitude = amplitude;
        this.changeAmount = changeAmount;
        this.changeRate = changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Quotation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.s_code
     *
     * @return the value of quotation.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.s_code
     *
     * @param sCode the value for quotation.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setsCode(String sCode) {
        this.sCode = sCode == null ? null : sCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.datetime
     *
     * @return the value of quotation.datetime
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.datetime
     *
     * @param datetime the value for quotation.datetime
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.time_interval
     *
     * @return the value of quotation.time_interval
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Byte getTimeInterval() {
        return timeInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.time_interval
     *
     * @param timeInterval the value for quotation.time_interval
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setTimeInterval(Byte timeInterval) {
        this.timeInterval = timeInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.now_price
     *
     * @return the value of quotation.now_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getNowPrice() {
        return nowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.now_price
     *
     * @param nowPrice the value for quotation.now_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setNowPrice(Float nowPrice) {
        this.nowPrice = nowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.open_price
     *
     * @return the value of quotation.open_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.open_price
     *
     * @param openPrice the value for quotation.open_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setOpenPrice(Float openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.close_price
     *
     * @return the value of quotation.close_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.close_price
     *
     * @param closePrice the value for quotation.close_price
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setClosePrice(Float closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.highest
     *
     * @return the value of quotation.highest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getHighest() {
        return highest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.highest
     *
     * @param highest the value for quotation.highest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setHighest(Float highest) {
        this.highest = highest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.lowest
     *
     * @return the value of quotation.lowest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getLowest() {
        return lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.lowest
     *
     * @param lowest the value for quotation.lowest
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setLowest(Float lowest) {
        this.lowest = lowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.volume
     *
     * @return the value of quotation.volume
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.volume
     *
     * @param volume the value for quotation.volume
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.turnover
     *
     * @return the value of quotation.turnover
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Long getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.turnover
     *
     * @param turnover the value for quotation.turnover
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setTurnover(Long turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.turnover_rate
     *
     * @return the value of quotation.turnover_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getTurnoverRate() {
        return turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.turnover_rate
     *
     * @param turnoverRate the value for quotation.turnover_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setTurnoverRate(Float turnoverRate) {
        this.turnoverRate = turnoverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.amplitude
     *
     * @return the value of quotation.amplitude
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getAmplitude() {
        return amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.amplitude
     *
     * @param amplitude the value for quotation.amplitude
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setAmplitude(Float amplitude) {
        this.amplitude = amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.change_amount
     *
     * @return the value of quotation.change_amount
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Long getChangeAmount() {
        return changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.change_amount
     *
     * @param changeAmount the value for quotation.change_amount
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setChangeAmount(Long changeAmount) {
        this.changeAmount = changeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotation.change_rate
     *
     * @return the value of quotation.change_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Float getChangeRate() {
        return changeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotation.change_rate
     *
     * @param changeRate the value for quotation.change_rate
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setChangeRate(Float changeRate) {
        this.changeRate = changeRate;
    }
}