package com.example.financial_info.entity;

import java.io.Serializable;

public class Stock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.s_id
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private String sCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.s_name
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.type
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Stock(Integer sId, String sCode, String sName, String type) {
        this.sId = sId;
        this.sCode = sCode;
        this.sName = sName;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Stock() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.s_id
     *
     * @return the value of stock.s_id
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.s_id
     *
     * @param sId the value for stock.s_id
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.s_code
     *
     * @return the value of stock.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public String getsCode() {
        return sCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.s_code
     *
     * @param sCode the value for stock.s_code
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setsCode(String sCode) {
        this.sCode = sCode == null ? null : sCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.s_name
     *
     * @return the value of stock.s_name
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.s_name
     *
     * @param sName the value for stock.s_name
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.type
     *
     * @return the value of stock.type
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.type
     *
     * @param type the value for stock.type
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}