package com.example.financial_info.mapper;

import com.example.financial_info.entity.OptionalStock;
import com.example.financial_info.entity.OptionalStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptionalStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    long countByExample(OptionalStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int deleteByExample(OptionalStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int insert(OptionalStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int insertSelective(OptionalStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    List<OptionalStock> selectByExample(OptionalStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    OptionalStock selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") OptionalStock record, @Param("example") OptionalStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByExample(@Param("record") OptionalStock record, @Param("example") OptionalStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByPrimaryKeySelective(OptionalStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table optional stock
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByPrimaryKey(OptionalStock record);
}