package com.example.financial_info.mapper;

import com.example.financial_info.entity.Quotation;
import com.example.financial_info.entity.QuotationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuotationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    long countByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int deleteByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int deleteByPrimaryKey(String sCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int insert(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int insertSelective(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    List<Quotation> selectByExample(QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    Quotation selectByPrimaryKey(String sCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") Quotation record, @Param("example") QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByExample(@Param("record") Quotation record, @Param("example") QuotationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByPrimaryKeySelective(Quotation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotation
     *
     * @mbg.generated Thu Apr 22 15:46:51 CST 2021
     */
    int updateByPrimaryKey(Quotation record);
}